/*************************************************************************
*                                                                        *
*  Copyright (c) 2014 Torben Bruchhaus                                   *
*  http://ffqueue.bruchhaus.dk/                                          *
*  File: bin_res.h                                                       *
*                                                                        *
*  This file is part of FFQueue.                                         *
*                                                                        *
*  FFQueue is free software: you can redistribute it and/or modify       *
*  it under the terms of the GNU General Public License as published by  *
*  the Free Software Foundation, either version 3 of the License, or     *
*  (at your option) any later version.                                   *
*                                                                        *
*  FFQueue is distributed in the hope that it will be useful,            *
*  but WITHOUT ANY WARRANTY; without even the implied warranty of        *
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
*  GNU General Public License for more details.                          *
*                                                                        *
*  You should have received a copy of the GNU General Public License     *
*  along with FFQueue.  If not, see <http://www.gnu.org/licenses/>.      *
*                                                                        *
*************************************************************************/

// BINARY RESOURCES GENERATED BY FFQUEUE DEBUG BUILD!

#ifndef BIN_RES_H
#define BIN_RES_H
#include "utils/FFQConst.h"

extern const uint32_t TOOL_ADD_SIZE;
extern const unsigned char TOOL_ADD[];

extern const uint32_t TOOL_BATCH_SIZE;
extern const unsigned char TOOL_BATCH[];

extern const uint32_t TOOL_EDIT_SIZE;
extern const unsigned char TOOL_EDIT[];

extern const uint32_t TOOL_DELETE_SIZE;
extern const unsigned char TOOL_DELETE[];

extern const uint32_t TOOL_START_SIZE;
extern const unsigned char TOOL_START[];

extern const uint32_t TOOL_STOP_SIZE;
extern const unsigned char TOOL_STOP[];

extern const uint32_t TOOL_CONFIG_SIZE;
extern const unsigned char TOOL_CONFIG[];

extern const uint32_t TOOL_ABOUT_SIZE;
extern const unsigned char TOOL_ABOUT[];

extern const uint32_t TOOL_TOOLS_SIZE;
extern const unsigned char TOOL_TOOLS[];

extern const uint32_t TOOL_PREVIEW_SIZE;
extern const unsigned char TOOL_PREVIEW[];

extern const uint32_t TOOL_PRESETS_SIZE;
extern const unsigned char TOOL_PRESETS[];

extern const uint32_t ICON_JOB_SIZE;
extern const unsigned char ICON_JOB[];

extern const uint32_t ICON_TOOL_SIZE;
extern const unsigned char ICON_TOOL[];

extern const uint32_t ICON_PLAY_DARK_SIZE;
extern const unsigned char ICON_PLAY_DARK[];

extern const uint32_t ICON_PLAY_LIGHT_SIZE;
extern const unsigned char ICON_PLAY_LIGHT[];

extern const uint32_t ICON_TAB_MSG_SIZE;
extern const unsigned char ICON_TAB_MSG[];

extern const uint32_t ICON_TAB_ON_SIZE;
extern const unsigned char ICON_TAB_ON[];

extern const uint32_t ICON_TAB_OFF_SIZE;
extern const unsigned char ICON_TAB_OFF[];

extern const uint32_t FLAG_ANIM_SIZE;
extern const unsigned char FLAG_ANIM[];

extern const uint32_t MAIN_LOGO_SIZE;
extern const unsigned char MAIN_LOGO[];

extern const uint32_t FONTS_CONF_SIZE;
extern const unsigned char FONTS_CONF[];

extern const uint32_t STR_ABOUT_SIZE;
extern const unsigned char STR_ABOUT[];

#endif //BIN_RES_H